# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptt_reserve.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ptt_reserve.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11ptt_reserve.proto\"\xbd\x01\n\x0bptt_reserve\x1a\xad\x01\n\rReserveStruct\x12\x1e\n\x13uint32_change_voice\x18\x01 \x01(\r:\x01\x30\x12\x1b\n\x13\x62ytes_general_flags\x18\x02 \x01(\x0c\x12\x1f\n\x14uint32_color_text_id\x18\x03 \x01(\r:\x01\x30\x12\x1e\n\x13uint32_redpack_type\x18\x05 \x01(\r:\x01\x30\x12\x1e\n\x16\x62ytes_redpack_score_id\x18\x06 \x01(\x0c')
)




_PTT_RESERVE_RESERVESTRUCT = _descriptor.Descriptor(
  name='ReserveStruct',
  full_name='ptt_reserve.ReserveStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uint32_change_voice', full_name='ptt_reserve.ReserveStruct.uint32_change_voice', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_general_flags', full_name='ptt_reserve.ReserveStruct.bytes_general_flags', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_color_text_id', full_name='ptt_reserve.ReserveStruct.uint32_color_text_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_redpack_type', full_name='ptt_reserve.ReserveStruct.uint32_redpack_type', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_redpack_score_id', full_name='ptt_reserve.ReserveStruct.bytes_redpack_score_id', index=4,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=211,
)

_PTT_RESERVE = _descriptor.Descriptor(
  name='ptt_reserve',
  full_name='ptt_reserve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_PTT_RESERVE_RESERVESTRUCT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=211,
)

_PTT_RESERVE_RESERVESTRUCT.containing_type = _PTT_RESERVE
DESCRIPTOR.message_types_by_name['ptt_reserve'] = _PTT_RESERVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ptt_reserve = _reflection.GeneratedProtocolMessageType('ptt_reserve', (_message.Message,), dict(

  ReserveStruct = _reflection.GeneratedProtocolMessageType('ReserveStruct', (_message.Message,), dict(
    DESCRIPTOR = _PTT_RESERVE_RESERVESTRUCT,
    __module__ = 'ptt_reserve_pb2'
    # @@protoc_insertion_point(class_scope:ptt_reserve.ReserveStruct)
    ))
  ,
  DESCRIPTOR = _PTT_RESERVE,
  __module__ = 'ptt_reserve_pb2'
  # @@protoc_insertion_point(class_scope:ptt_reserve)
  ))
_sym_db.RegisterMessage(ptt_reserve)
_sym_db.RegisterMessage(ptt_reserve.ReserveStruct)


# @@protoc_insertion_point(module_scope)
