# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubMsgType0x1a.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubMsgType0x1a.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14SubMsgType0x1a.proto\"\x9f\x02\n\x0eSubMsgType0x1a\x1a\x8c\x02\n\x07MsgBody\x12\x16\n\x0e\x62ytes_file_key\x18\x01 \x01(\x0c\x12\x1a\n\x0fuint32_from_uin\x18\x02 \x01(\r:\x01\x30\x12\x18\n\ruint32_to_uin\x18\x03 \x01(\r:\x01\x30\x12\x18\n\ruint32_status\x18\x04 \x01(\r:\x01\x30\x12\x15\n\nuint32_ttl\x18\x05 \x01(\r:\x01\x30\x12\x13\n\x0bstring_desc\x18\x06 \x01(\t\x12\x16\n\x0buint32_type\x18\x07 \x01(\r:\x01\x30\x12\x1f\n\x14uint32_capture_times\x18\x08 \x01(\r:\x01\x30\x12\x1a\n\x0fuint64_from_uin\x18\t \x01(\x04:\x01\x30\x12\x18\n\ruint64_to_uin\x18\n \x01(\x04:\x01\x30')
)




_SUBMSGTYPE0X1A_MSGBODY = _descriptor.Descriptor(
  name='MsgBody',
  full_name='SubMsgType0x1a.MsgBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes_file_key', full_name='SubMsgType0x1a.MsgBody.bytes_file_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_from_uin', full_name='SubMsgType0x1a.MsgBody.uint32_from_uin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_to_uin', full_name='SubMsgType0x1a.MsgBody.uint32_to_uin', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_status', full_name='SubMsgType0x1a.MsgBody.uint32_status', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_ttl', full_name='SubMsgType0x1a.MsgBody.uint32_ttl', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_desc', full_name='SubMsgType0x1a.MsgBody.string_desc', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_type', full_name='SubMsgType0x1a.MsgBody.uint32_type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_capture_times', full_name='SubMsgType0x1a.MsgBody.uint32_capture_times', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint64_from_uin', full_name='SubMsgType0x1a.MsgBody.uint64_from_uin', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint64_to_uin', full_name='SubMsgType0x1a.MsgBody.uint64_to_uin', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=312,
)

_SUBMSGTYPE0X1A = _descriptor.Descriptor(
  name='SubMsgType0x1a',
  full_name='SubMsgType0x1a',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_SUBMSGTYPE0X1A_MSGBODY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=312,
)

_SUBMSGTYPE0X1A_MSGBODY.containing_type = _SUBMSGTYPE0X1A
DESCRIPTOR.message_types_by_name['SubMsgType0x1a'] = _SUBMSGTYPE0X1A
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubMsgType0x1a = _reflection.GeneratedProtocolMessageType('SubMsgType0x1a', (_message.Message,), dict(

  MsgBody = _reflection.GeneratedProtocolMessageType('MsgBody', (_message.Message,), dict(
    DESCRIPTOR = _SUBMSGTYPE0X1A_MSGBODY,
    __module__ = 'SubMsgType0x1a_pb2'
    # @@protoc_insertion_point(class_scope:SubMsgType0x1a.MsgBody)
    ))
  ,
  DESCRIPTOR = _SUBMSGTYPE0X1A,
  __module__ = 'SubMsgType0x1a_pb2'
  # @@protoc_insertion_point(class_scope:SubMsgType0x1a)
  ))
_sym_db.RegisterMessage(SubMsgType0x1a)
_sym_db.RegisterMessage(SubMsgType0x1a.MsgBody)


# @@protoc_insertion_point(module_scope)
