# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncookie.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='syncookie.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fsyncookie.proto\"\xa8\x02\n\tSynCookie\x12\x11\n\x06tag_01\x18\x01 \x01(\x04:\x01\x30\x12\x11\n\x06tag_02\x18\x02 \x01(\x04:\x01\x30\x12\x11\n\x06tag_03\x18\x03 \x01(\x04:\x01\x30\x12\x11\n\x06tag_04\x18\x04 \x01(\x04:\x01\x30\x12\x11\n\x06tag_05\x18\x05 \x01(\x04:\x01\x30\x12\x11\n\x06tag_06\x18\x06 \x01(\x04:\x01\x30\x12\x11\n\x06tag_07\x18\x07 \x01(\x04:\x01\x30\x12\x11\n\x06tag_08\x18\x08 \x01(\x04:\x01\x30\x12\x11\n\x06tag_09\x18\t \x01(\x04:\x01\x30\x12\x11\n\x06tag_10\x18\n \x01(\x04:\x01\x30\x12\x11\n\x06tag_11\x18\x0b \x01(\x04:\x01\x30\x12\x11\n\x06tag_12\x18\x0c \x01(\x04:\x01\x30\x12\x11\n\x06tag_13\x18\r \x01(\x04:\x01\x30\x12\x11\n\x06tag_14\x18\x0e \x01(\x04:\x01\x30\x12\x11\n\x06tag_15\x18\x0f \x01(\x04:\x01\x30')
)




_SYNCOOKIE = _descriptor.Descriptor(
  name='SynCookie',
  full_name='SynCookie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_01', full_name='SynCookie.tag_01', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_02', full_name='SynCookie.tag_02', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_03', full_name='SynCookie.tag_03', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_04', full_name='SynCookie.tag_04', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_05', full_name='SynCookie.tag_05', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_06', full_name='SynCookie.tag_06', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_07', full_name='SynCookie.tag_07', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_08', full_name='SynCookie.tag_08', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_09', full_name='SynCookie.tag_09', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_10', full_name='SynCookie.tag_10', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_11', full_name='SynCookie.tag_11', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_12', full_name='SynCookie.tag_12', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_13', full_name='SynCookie.tag_13', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_14', full_name='SynCookie.tag_14', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_15', full_name='SynCookie.tag_15', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['SynCookie'] = _SYNCOOKIE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SynCookie = _reflection.GeneratedProtocolMessageType('SynCookie', (_message.Message,), dict(
  DESCRIPTOR = _SYNCOOKIE,
  __module__ = 'syncookie_pb2'
  # @@protoc_insertion_point(class_scope:SynCookie)
  ))
_sym_db.RegisterMessage(SynCookie)


# @@protoc_insertion_point(module_scope)
